import {expect, test} from '@playwright/test'
import { BlazeDemo_FlightPurchase } from './page_objects/reserve_flight_form'
import logger from '../../util/loggger'
declare const process: {env: {[key: string]: string | undefined}}
const getEnvValue = (key: string, fallout: string): string => process.env[key] ?? fallout

test.beforeEach(async({page}) => {
    const negativeTestForm = new BlazeDemo_FlightPurchase(page as any)
    const referenceTitle = getEnvValue('BLAZEDEMO_PURCHASE_VIRGINN_AMERICA_TITLE', 'BlazeDemo Purchase')
    const referenceEndpoint = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_ENDPOINT', 'blazedemo')
    await logger.info(`tests/reserved_flight_purchase_forms/negative_test_reserved_flight_purchase_form.spec.ts: Test execution for negative testing on flight purchase forms`)
    await negativeTestForm.gotoWebsiteSource()
    await expect(page).toHaveTitle(referenceTitle)
    await expect(page.url()).toContain(referenceEndpoint)
})
test("Submit a form with a blank name text field while using a Visa card for purchasing a reserved flight for Virgin America", async({page}) => {
    const referenceAddress= getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_ADDRESS', 'blazedemo')
    const referenceCity = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_CITY', 'blazedemo')
    const referenceState = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_STATE', 'blazedemo')
    const referenceZipCode = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_ZIP_CODE', 'blazedemo')
    const referenceCreditCardNumber = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_CREDIT_CARD_NUMBER', 'blazedemo')
    const referenceCreditCardMonth = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_CREDIT_CARD_MONTH', 'blazedemo')
    const referenceCreditCardYear = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_CREDIT_CARD_YEAR', 'blazedemo')
    const referenceNameOnCard = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_NAME_ON_CARD', 'blazedemo')
    const negativeTestForm = new BlazeDemo_FlightPurchase(page as any)
    await negativeTestForm.negative_test_reserved_flight_form_blank_name(referenceAddress, referenceCity, referenceState, referenceZipCode, 
                referenceCreditCardNumber, referenceCreditCardMonth, referenceCreditCardYear, referenceNameOnCard)
    await negativeTestForm.select_card_visa()
    await negativeTestForm.checkbox()
    await negativeTestForm.submitButton()
})
test("Submit a form with a blank address text field while using a Visa card for purchasing a reserved flight for Virgin America", async({page}) => {
    const referenceName = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_NAME', 'blazedemo')
    const referenceCity = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_CITY', 'blazedemo')
    const referenceState = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_STATE', 'blazedemo')
    const referenceZipCode = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_ZIP_CODE', 'blazedemo')
    const referenceCreditCardNumber = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_CREDIT_CARD_NUMBER', 'blazedemo')
    const referenceCreditCardMonth = getEnvValue('BLAZEDEMO_PURCHASE_CREDIT_CARD_MONTH', 'blazedemo')
    const referenceCreditCardYear = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_CREDIT_CARD_YEAR', 'blazedemo')
    const referenceNameOnCard = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_NAME_ON_CARD', 'blazedemo')
    const negativeTestForm = new BlazeDemo_FlightPurchase(page as any)
    await negativeTestForm.negative_test_reserved_flight_form_blank_address(referenceName, referenceCity, referenceState, referenceZipCode, 
                referenceCreditCardNumber, referenceCreditCardMonth, referenceCreditCardYear, referenceNameOnCard)
    await negativeTestForm.select_card_visa()
    await negativeTestForm.checkbox()
    await negativeTestForm.submitButton()
})
test("Submit a form with a blank city text field while using a Visa card for purchasing a reserved flight for Virgin America", async({page}) => {
    const referenceName = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_NAME', 'blazedemo')
    const referenceAddress = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_ADDRESS', 'blazedemo')
    const referenceState = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_STATE', 'blazedemo')
    const referenceZipCode = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_ZIP_CODE', 'blazedemo')
    const referenceCreditCardNumber = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_CREDIT_CARD_NUMBER', 'blazedemo')
    const referenceCreditCardMonth = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_MONTH', 'blazedemo')
    const referenceCreditCardYear = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_YEAR', 'blazedemo')
    const referenceNameOnCard = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_NAME_ON_CARD', 'blazedemo')
    const negativeTestForm = new BlazeDemo_FlightPurchase(page as any)
    await negativeTestForm.negative_test_reserved_flight_form_blank_city(referenceName, referenceAddress, referenceState, referenceZipCode, 
                referenceCreditCardNumber, referenceCreditCardMonth, referenceCreditCardYear, referenceNameOnCard)
    await negativeTestForm.select_card_visa()
    await negativeTestForm.checkbox()
    await negativeTestForm.submitButton()
})
test("Submit a form with a blank state text field while using a Visa card for purchasing a reserved flight for Virgin America", async({page}) => {
    const referenceName = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_NAME', 'blazedemo')
    const referenceAddress = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_ADDRESS', 'blazedemo')
    const referenceCity = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_CITY', 'blazedemo')
    const referenceZipCode = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_ZIP_CODE', 'blazedemo')
    const referenceCreditCardNumber = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_CREDIT_CARD_NUMBER', 'blazedemo')
    const referenceCreditCardMonth = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_MONTH', 'blazedemo')
    const referenceCreditCardYear = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_YEAR', 'blazedemo')
    const referenceNameOnCard = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_NAME_ON_CARD', 'blazedemo')
    const negativeTestForm = new BlazeDemo_FlightPurchase(page as any)
    await negativeTestForm.negative_test_reserved_flight_form_blank_state(referenceName, referenceAddress, referenceCity, referenceZipCode, 
                referenceCreditCardNumber, referenceCreditCardMonth, referenceCreditCardYear, referenceNameOnCard)
    await negativeTestForm.select_card_visa()
    await negativeTestForm.checkbox()
    await negativeTestForm.submitButton()
})
test("Submit a form with a blank zip code text field while using a Visa card for purchasing a reserved flight for Virgin America", async({page}) => {
    const referenceName = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_NAME', 'blazedemo')
    const referenceAddress = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_ADDRESS', 'blazedemo')
    const referenceCity = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_CITY', 'blazedemo')
    const referenceState = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_STATE', 'blazedemo')
    const referenceCreditCardNumber = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_CREDIT_CARD_NUMBER', 'blazedemo')
    const referenceCreditCardMonth = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_MONTH', 'blazedemo')
    const referenceCreditCardYear = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_YEAR', 'blazedemo')
    const referenceNameOnCard = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_NAME_ON_CARD', 'blazedemo')
    const negativeTestForm = new BlazeDemo_FlightPurchase(page as any)
    await negativeTestForm.negative_test_reserved_flight_form_blank_zip_code(referenceName, referenceAddress, referenceCity, referenceState, 
                referenceCreditCardNumber, referenceCreditCardMonth, referenceCreditCardYear, referenceNameOnCard)
    await negativeTestForm.select_card_visa()
    await negativeTestForm.checkbox()
    await negativeTestForm.submitButton()
})
test("Submit a form with a blank credit card number text field while using a Visa card for purchasing a reserved flight for Virgin America", async({page}) => {
    const referenceName = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_NAME', 'blazedemo')
    const referenceAddress = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_ADDRESS', 'blazedemo')
    const referenceCity = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_CITY', 'blazedemo')
    const referenceState = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_STATE', 'blazedemo')
    const referenceZipCode = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_ZIP_CODE', 'blazedemo')
    const referenceCreditCardMonth = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_MONTH', 'blazedemo')
    const referenceCreditCardYear = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_YEAR', 'blazedemo')
    const referenceNameOnCard = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_NAME_ON_CARD', 'blazedemo')
    const negativeTestForm = new BlazeDemo_FlightPurchase(page as any)
    await negativeTestForm.negative_test_reserved_flight_form_blank_credit_card_number(referenceName, referenceAddress, referenceCity, referenceState, referenceZipCode, 
                referenceCreditCardMonth, referenceCreditCardYear, referenceNameOnCard)
    await negativeTestForm.select_card_visa()
    await negativeTestForm.checkbox()
    await negativeTestForm.submitButton()
})
test("Submit a form with a blank month text field while using a Visa card for purchasing a reserved flight for Virgin America", async({page}) => {
    const referenceName = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_NAME', 'blazedemo')
    const referenceAddress = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_ADDRESS', 'blazedemo')
    const referenceCity = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_CITY', 'blazedemo')
    const referenceState = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_STATE', 'blazedemo')
    const referenceZipCode = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_ZIP_CODE', 'blazedemo')
    const referenceCreditCardNumber = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_CREDIT_CARD_NUMBER', 'blazedemo')
    const referenceCreditCardYear = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_YEAR', 'blazedemo')
    const referenceNameOnCard = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_NAME_ON_CARD', 'blazedemo')
    const negativeTestForm = new BlazeDemo_FlightPurchase(page as any)
    await negativeTestForm.negative_test_reserved_flight_form_blank_month(referenceName, referenceAddress, referenceCity, referenceState, referenceZipCode, 
                referenceCreditCardNumber, referenceCreditCardYear, referenceNameOnCard)
    await negativeTestForm.select_card_visa()
    await negativeTestForm.checkbox()
    await negativeTestForm.submitButton()
})
test("Submit a form with a blank year text field while using a Visa card for purchasing a reserved flight for Virgin America", async({page}) => {
    const referenceName = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_NAME', 'blazedemo')
    const referenceAddress = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_ADDRESS', 'blazedemo')
    const referenceCity = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_CITY', 'blazedemo')
    const referenceState = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_STATE', 'blazedemo')
    const referenceZipCode = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_ZIP_CODE', 'blazedemo')
    const referenceCreditCardNumber = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_CREDIT_CARD_NUMBER', 'blazedemo')
    const referenceCreditCardMonth = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_MONTH', 'blazedemo')
    const referenceNameOnCard = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_NAME_ON_CARD', 'blazedemo')
    const negativeTestForm = new BlazeDemo_FlightPurchase(page as any)
    await negativeTestForm.negative_test_reserved_flight_form_blank_year(referenceName, referenceAddress, referenceCity, referenceState, referenceZipCode, 
                referenceCreditCardNumber, referenceCreditCardMonth, referenceNameOnCard)
    await negativeTestForm.select_card_visa()
    await negativeTestForm.checkbox()
    await negativeTestForm.submitButton()
})
test("Submit a form with a blank 'name on card' text field while using a Visa card for purchasing a reserved flight for Virgin America", async({page}) => {
    const referenceName = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_NAME', 'blazedemo')
    const referenceAddress = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_ADDRESS', 'blazedemo')
    const referenceCity = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_CITY', 'blazedemo')
    const referenceState = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_STATE', 'blazedemo')
    const referenceZipCode = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_ZIP_CODE', 'blazedemo')
    const referenceCreditCardNumber = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_CREDIT_CARD_NUMBER', 'blazedemo')
    const referenceCreditCardMonth = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_MONTH', 'blazedemo')
    const referenceCreditCardYear = getEnvValue('BLAZEDEMO_PURCHASE_VIRGIN_AMERICA_YEAR', 'blazedemo')
    const negativeTestForm = new BlazeDemo_FlightPurchase(page as any)
    await negativeTestForm.negative_test_reserved_flight_form_blank_name_on_card(referenceName, referenceAddress, referenceCity, referenceState, referenceZipCode, 
                referenceCreditCardNumber, referenceCreditCardMonth, referenceCreditCardYear)
    await negativeTestForm.select_card_visa()
    await negativeTestForm.checkbox()
    await negativeTestForm.submitButton()
})
test.afterEach(async({page}, testInfo) => {
     const negativeTestForm = new BlazeDemo_FlightPurchase(page as any)
     const status = testInfo.status ?? 'undefined'
     if (status === 'failed'){
        await logger.error(`tests/reserved_flight_purchase_forms/negative_test_reserved_flight_purchase_form.spec.ts: Testy execution failed at step "${testInfo.title}"`)
     } else {
        await logger.info(`tests/reserved_flight_purchase_forms/negative_test_reserved_flight_purchase_form.spec.ts: Test execution completed with status ${testInfo.status?.toUpperCase()}`)
     }
     await negativeTestForm.close()
})
