name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  # 1. Run the test
  run-tests:
    runs-on: ubuntu-latest
    # 2. Implement strategy
    strategy:
      # 3. Implement matrix
      matrix:
        # 4. Sharing
        shard: [1, 2, 3]
    # Implement steps and run commands
    # 1. Implement steps
    steps:
      # 2. Implement checkout code
      - name: Checkout code
        uses: actions/checkout@v4
    # Run commands
    # 1. Execute the run commmand
      - name: Run tests
      # 2. Make directory for output reports with matrix sharing 
        run: |
          mkdir -p output-reports
          echo "Results from Shard ${{matrix.shard}}" > output-reports/report-${{matrix.shard}}.txt
    # Upload shard report by using upload artifact tool
    # 1. Implement the upload artifact tool  
      - name: Upload Shard Report
        uses: actions/upload-artifact@v4
        # 2. Use the test report shard matrix and output reports folder
        with:
          name: test-reports-shard-${{matrix.shard}}
          path: output-reports/
          # 3. Set the retention days
          retention-days: 1
  
  # Merge the reports
  merge-reports:
    runs-on: ubuntu-latest
    # 1. Implement needs command to run-tests
    needs: run-tests
    # 2. Implement steps 
    steps:
      # 3. Implement checkout code tool
      - name: Checkout code
        uses: actions/checkout@v4
      # 4. Implement download artifact tool 
      - name: Download All Shard reports
        uses: actions/download-artifact@v4
        # Use report command patterns for testing reports
        with:
          # 1. Set the pattern for test-reports-shard command
          pattern: test-reports-shard
          # 2. Set the path for the merge-reports command
          path: merge-reports
          # 3. Set merge-multiple to true
          merge-multiple: true
      # Merge the reports
      - name: Merge Report Processing
      # 1. Implement run command to concatentate the folders
        run: |
          echo "=== Combining Reports ==="
          ls -R
          cat merge-reports/*.txt > final-combined-report.txt
          cat final-combined-report.txt
      # Upload the reports
      # 1. Implement the upload tool artifact
      - name: Upload Final Unified Report
        uses: actions/upload-artifact@v4
        # 2. Use with the final combined report that was concatenated
        with:
          name: final-combined-report
          path: final-combined-report.txt
